### ISSUE TITLE
getTitlesWidget error in console.

### ISSUE THREAD

**Issue by chengweiou** [imaNNeoFighT/fl_chart#1001]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

After I upgrade to flutter 3

**To Reproduce**

no matter I comment or not
      rightTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        // getTitlesWidget: (v, meta) => Text('$v', style: TextStyle(color: Proj().color.gray2, fontSize: 8)),
      )));

**Screenshots**

When I use my widget
```
═╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 43 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Text
  Text:file:///usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.1/lib/src/chart/base/base_chart/base_chart_data.dart:194:10

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:43:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4741:12)
#4      TextPainter.paint (package:flutter/src/painting/text_painter.dart:696:12)
#5      RenderParagraph.paint (package:flutter/src/rendering/paragraph.dart:742:18)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#9      AxisSideTitlesRenderFlex.paint (package:fl_chart/src/chart/base/axis_chart/side_titles/side_titles_flex.dart:252:5)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#15     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#19     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#22     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#25     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#26     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#27     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#30     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:340:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#36     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#39     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#40     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#43     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#44     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#47     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#48     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:598:11)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#52     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#53     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#59     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#61     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#62     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#63     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#64     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:506:19)
#65     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#66     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#67     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#68     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#69     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderParagraph#82195 relayoutBoundary=up1:
  creator: RichText ← Text ← SideTitlesFlex ← ConstrainedBox ← Padding ← Container ← Flex ← Align ←
    SideTitlesWidget ← Stack ← LayoutBuilder ← AxisChartScaffoldWidget ← ⋯
  parentData: offset=Offset(0.0, NaN); flex=null; fit=null (can use size)
  constraints: BoxConstraints(w=20.0, 0.0<=h<=Infinity)
  size: Size(20.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
This RenderObject had the following child:
    text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
Performing hot reload...                                                
Reloaded 3 of 2438 libraries in 1,761ms.

Another exception was thrown: Offset argument contained a NaN value.
```

When I use default

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 43 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Text
  Text:file:///usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.1/lib/src/chart/base/base_chart/base_chart_data.dart:194:10

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:43:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4741:12)
#4      TextPainter.paint (package:flutter/src/painting/text_painter.dart:696:12)
#5      RenderParagraph.paint (package:flutter/src/rendering/paragraph.dart:742:18)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#9      AxisSideTitlesRenderFlex.paint (package:fl_chart/src/chart/base/axis_chart/side_titles/side_titles_flex.dart:252:5)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#15     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#19     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#22     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#25     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#26     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#27     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#30     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:340:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#36     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#39     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#40     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#43     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#44     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#47     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#48     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:598:11)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#52     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#53     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#59     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#61     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#62     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#63     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#64     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:506:19)
#65     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#66     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#67     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#68     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#69     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#73     _invoke (dart:ui/hooks.dart:151:10)
#74     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#75     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)

The following RenderObject was being processed when the exception was fired: RenderParagraph#159f8 relayoutBoundary=up1:
  creator: RichText ← Text ← SideTitlesFlex ← ConstrainedBox ← Padding ← Container ← Flex ← Align ←
    SideTitlesWidget ← Stack ← LayoutBuilder ← AxisChartScaffoldWidget ← ⋯
  parentData: offset=Offset(0.0, NaN); flex=null; fit=null (can use size)
  constraints: BoxConstraints(w=20.0, 0.0<=h<=Infinity)
  size: Size(20.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
This RenderObject had the following child:
    text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Offset argument contained a NaN value.
```

**Versions**
 - which version of the Flutter are you using?
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
    ! Error: Failed to prepare device for development. Please unlock and reconnect the device. (code 806)
[✓] HTTP Host Availability

 - which version of the FlChart are you using?
latest

**Comment by imaNNeoFighT** [comment]
Any reproducible code?

**Comment by chengweiou** [comment]
it work normal before I upgrade flutter.
```
BarChart(
        BarChartData(
          titlesData: titlesData,
          borderData: FlBorderData(border: Border(left: BorderSide(color: someColor), bottom: BorderSide(color: someColor))),
          barGroups: barGroups,
          alignment: BarChartAlignment.spaceAround,
        ),
      );

FlTitlesData get titlesData => FlTitlesData(
      bottomTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        getTitlesWidget: (v, meta) => Text('someText'),
      )),
      leftTitles: AxisTitles(sideTitles: SideTitles()),
      topTitles: AxisTitles(sideTitles: SideTitles()),
      rightTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        // todo  https://github.com/imaNNeoFighT/fl_chart/issues/1001
        getTitlesWidget: (v, meta) => Text('$v', style: TextStyle(color: someColor, fontSize: 8)),
      )));
  List<BarChartGroupData> get barGroups => List.generate(
        someListLength,
        (i) => BarChartGroupData(x: i + 1, barRods: [
          BarChartRodData(
              toY: someDouble,
              width: 20,
              borderRadius: BorderRadius.zero,
              color: someColor)
        ]),
      );
```

**Comment by chengweiou** [comment]
```
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);
  // This widget is the root of your application.
  @override
  build(ctx) => BarChart(
        BarChartData(
          titlesData: titlesData,
          borderData: FlBorderData(border: Border(left: BorderSide(color: Colors.red), bottom: BorderSide(color: Colors.red))),
          barGroups: barGroups,
          alignment: BarChartAlignment.spaceAround,
        ),
      );
  FlTitlesData get titlesData => FlTitlesData(
      bottomTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        getTitlesWidget: (v, meta) => Text('someText'),
      )),
      leftTitles: AxisTitles(sideTitles: SideTitles()),
      topTitles: AxisTitles(sideTitles: SideTitles()),
      rightTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        // todo  https://github.com/imaNNeoFighT/fl_chart/issues/1001
        getTitlesWidget: (v, meta) => Text('$v', style: TextStyle(color: Colors.red, fontSize: 8)),
      )));
  List<BarChartGroupData> get barGroups => List.generate(
        100,
        (i) => BarChartGroupData(x: i + 1, barRods: [BarChartRodData(toY: 100, width: 20, borderRadius: BorderRadius.zero, color: Colors.red)]),
      );
}

```

**Comment by chengweiou** [comment]
i found out one is because toY is 0

```
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(_Chart());
}

class _Chart extends StatelessWidget {
  @override
  build(ctx) => MaterialApp(
        home: BarChart(
          BarChartData(
            titlesData: titlesData,
            borderData: FlBorderData(border: Border(left: BorderSide(color: Colors.red), bottom: BorderSide(color: Colors.red))),
            barGroups: barGroups,
            alignment: BarChartAlignment.spaceAround,
          ),
        ),
      );

  FlTitlesData get titlesData => FlTitlesData(
      bottomTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        getTitlesWidget: (v, meta) => Text('aaa'),
      )),
      leftTitles: AxisTitles(sideTitles: SideTitles()),
      topTitles: AxisTitles(sideTitles: SideTitles()),
      rightTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        // getTitlesWidget: (v, meta) => Text('$v', style: TextStyle(color: Colors.red, fontSize: 8)),
      )));
  List<BarChartGroupData> get barGroups => List.generate(
        100,
        (i) => BarChartGroupData(x: i + 1, barRods: [BarChartRodData(toY: 0, width: 20, borderRadius: BorderRadius.zero, color: Colors.red)]),
      );
}

```

**Comment by imaNNeoFighT** [comment]
You should use either MaterialApp or CupertinoApp as a root widget.

Check the code below:
```dart
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  build(ctx) => MaterialApp(
        home: Scaffold(
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(20.0),
              child: AspectRatio(
                aspectRatio: 2,
                child: BarChart(
                  BarChartData(
                    titlesData: titlesData,
                    borderData: FlBorderData(
                        border: Border(
                            left: BorderSide(color: Colors.red),
                            bottom: BorderSide(color: Colors.red))),
                    barGroups: barGroups,
                    alignment: BarChartAlignment.spaceAround,
                  ),
                ),
              ),
            ),
          ),
        ),
      );

  FlTitlesData get titlesData => FlTitlesData(
      bottomTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        getTitlesWidget: (v, meta) => Text('someText'),
      )),
      leftTitles: AxisTitles(sideTitles: SideTitles()),
      topTitles: AxisTitles(sideTitles: SideTitles()),
      rightTitles: AxisTitles(
          sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 20,
        // todo  https://github.com/imaNNeoFighT/fl_chart/issues/1001
        getTitlesWidget: (v, meta) => Text('$v'),
      )));

  List<BarChartGroupData> get barGroups => List.generate(
        10,
        (i) => BarChartGroupData(x: i + 1, barRods: [
          BarChartRodData(
              toY: 100,
              width: 20,
              borderRadius: BorderRadius.zero,
              color: Colors.red)
        ]),
      );
}
```

**Comment by adrianvintu** [comment]
I got the same error using fl_chart: ^0.50.6
I updated to fl_chart: ^0.55.0 and the problem is gone.
Magic!
