### ISSUE TITLE
LineChart inside PageView breaks the pan gesture.

### ISSUE THREAD

**Issue by jamesblasco** [imaNNeoFighT/fl_chart#202]
In the example project, `LineChart` doesn't change the tooltip when dragging  through the widget.
This is because `PageView` is using a `HorizontalDragGestureRecognizer` that has priority to the `PanGestureRecognizer` that is used on the `LineChart`(the gesture detector widget with onPanStart...)

My proposal is to add:

onHorizontalDragDown 
onHorizontalDragStart 
onHorizontalDragUpdate
onHorizontalDragEnd 
onHorizontalDragCancel

with the same params of

onPanDown
onPanStart
onPanUpdate
onPanEnd
onPanCancel

This will make the LineChart have priority to the PageView.

To make it more adaptable we could add the param `draggable:bool` to `LineTouchData` in case people want to disable the pan gesture to prioritize other gestures in the Gesture Arena

**Comment by imaNNeoFighT** [comment]
Hi,
I didn't think about it, because I intentionally restricted it to work with long-press if it is in a scrollable parent.
but let me think about it, and let it be open.
Thanks for reporting.

**Comment by jamesblasco** [comment]
Thanks! I understand why you would want it like that. I will use my fork in the meantime.

Amazing work you are doing!! Thanks again

**Comment by dkobia** [comment]
I too I'm experiencing an issue with a barchart inside a SingleChildScrollview:

```
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'length' was called on null.
Receiver: null
Tried calling: length

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      BarChartPainter._getNearestTouchedSpot (package:fl_chart/src/chart/bar_chart/bar_chart_painter.dart:577:43)
#2      BarChartPainter.handleTouch (package:fl_chart/src/chart/bar_chart/bar_chart_painter.dart:564:9)
#3      _BarChartState.build.<anonymous closure> (package:fl_chart/src/chart/bar_chart/bar_chart.dart:84:58)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onCancel"
Recognizer: PanGestureRecognizer#defd2
  debugOwner: GestureDetector
  start behavior: start
```

It looks like this bit of commented out code might help? https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_painter.dart#L571

```
if (groupBarsPosition == null) {
  return null;
}
```

**Comment by FMorschel** [comment]
For me, it doesn't work inside a `ListView.builder` as well

**Comment by FMorschel** [comment]
> I will use my fork in the meantime.

Hi @jamesblasco, sorry for this direct mention. Could you please link your fork here for us?

**Comment by FMorschel** [comment]
I was looking at #268 and could not find the same code on the current version. Is there a workaround for it?

**Comment by xeinebiu** [comment]
> Hi, I didn't think about it, because I intentionally restricted it to work with long-press if it is in a scrollable parent. but let me think about it, and let it be open. Thanks for reporting.

Any update on this issue?

Rendering the LineChart inside horizontal scrollable parent works as you wrote by long press but not consistent, to have the same widget in multiple places with different behavior.
