### ISSUE TITLE
java.lang.SecurityException: Permission Denial

### ISSUE THREAD

**Issue by harpreet-applify** [imaNNeoFighT/fl_chart#834]
**Describe the bug**
Example fails to launch.
I've added `<uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL" />` as the error message suggests.

**To Reproduce**
```
Launching lib/main.dart on SM N950F in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53631/ptKhfUvRWL0=/ws
I/flchart.exampl(27981): Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()
D/vndksupport(27981): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
E/flutter (27981): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
E/flutter (27981): 	at android.os.Parcel.createException(Parcel.java:1966)
E/flutter (27981): 	at android.os.Parcel.readException(Parcel.java:1934)
E/flutter (27981): 	at android.os.Parcel.readException(Parcel.java:1884)
E/flutter (27981): 	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:7312)
E/flutter (27981): 	at android.app.Activity.reportFullyDrawn(Activity.java:2092)
E/flutter (27981): 	at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:1061)
E/flutter (27981): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:88)
E/flutter (27981): 	at io.flutter.embedding.android.FlutterView$2.onFlutterUiDisplayed(FlutterView.java:133)
E/flutter (27981): 	at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(FlutterJNI.java:461)
E/flutter (27981): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27981): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (27981): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (27981): 	at android.app.ActivityThread.main(ActivityThread.java:7073)
E/flutter (27981): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27981): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter (27981): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter (27981): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (27981): 	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1818)
E/flutter (27981): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25781)
E/flutter (27981): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25712)
E/flutter (27981): 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26582)
E/flutter (27981): 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1264)
E/flutter (27981):
E/flutter (27981):
F/flutter (27981): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1201)] Check failed: fml::jni::CheckException(env).
F/libc    (27981): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27981 (flchart.example), pid 27981 (flchart.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/greatltexx/greatlte:9/PPR1.180610.011/N950FXXSEDTL1:user/release-keys'
Revision: '9'
ABI: 'arm64'
pid: 27981, tid: 27981, name: flchart.example  >>> dev.flchart.example <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1201)] Check failed: fml::jni::CheckException(env).
'
    x0  0000000000000000  x1  0000000000006d4d  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  8000000000000000
    x8  0000000000000083  x9  00000076e21f8838  x10 fffffff87ffffbdf  x11 0000000000000001
    x12 0000007638d50c80  x13 0000000000000000  x14 ffffffffffffffff  x15 00004110d9d7d5a8
    x16 00000076e222f2a0  x17 00000076e216e920  x18 0000007fe54f2a9a  x19 0000000000006d4d
    x20 0000000000006d4d  x21 0000000000000083  x22 0000000000000034  x23 000000765c5bc430
    x24 000000765c5bc418  x25 0000000000000000  x26 00000076e2e0f5f8  x27 0000000000000034
    x28 0000000000000001  x29 0000007fe54f3350
    sp  0000007fe54f3310  lr  00000076e2161d68  pc  00000076e2161d94
backtrace:
    #00 pc 0000000000021d94  /system/lib64/libc.so (abort+124)
    #01 pc 000000000145a1dc  /data/app/dev.flchart.example-9AhcNIXDu5aIJLzoWG6OEA==/lib/arm64/libflutter.so (offset 0x1458000)
Lost connection to device.
Exited (sigterm)

```
**Versions**
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/dev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Users/dev/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • SM N950F (mobile) • ce10171ac02ea43b037e • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 96.0.4664.55
```
 - which version of the FlChart are you using? 
 `^0.40.2`

**Comment by harpreet-applify** [comment]
Did `flutter run` after uninstalling the app and it ran fine

**Comment by harpreet-applify** [comment]
Still facing this. Did `flutter clean`, unsinstalled the existing app.

**Comment by imaNNeoFighT** [comment]
Dude, I'm pretty sure it is not related to this library.
Try to remove the `fl_chart` dependency and let me know is it happening or not.

**Comment by harpreet-applify** [comment]
> Dude, I'm pretty sure it is not related to this library. Try to remove the `fl_chart` dependency and let me know is it happening or not.

You're correct, I commented all the samples and removed the package and this error persists.
