### ISSUE TITLE
Assertions to validate input

### ISSUE THREAD

**Issue by abdullatif-k** [imaNNeoFighT/fl_chart#908]
Here is a snippet of an error message I got

```
I/flutter ( 9042): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9042): The following UnsupportedError was thrown during paint():
I/flutter ( 9042): Unsupported operation: Result of truncating division is Infinity or NaN
I/flutter ( 9042): 
I/flutter ( 9042): The relevant error-causing widget was:
I/flutter ( 9042):   LineChartLeaf
I/flutter ( 9042):   LineChartLeaf:file:///home/user/Documents/Work/Scrap/Flutter_test/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.41.0/lib/src/chart/line_chart/line_chart.dart:48:12
I/flutter ( 9042): 
I/flutter ( 9042): When the exception was thrown, this was the stack:
I/flutter ( 9042): #0      double._trunc_div (dart:core-patch/double.dart:56:57)
I/flutter ( 9042): #1      double.~/ (dart:core-patch/double.dart:52:12)
I/flutter ( 9042): #2      AxisChartPainter._drawGrid (package:fl_chart/src/chart/base/axis_chart/axis_chart_painter.dart:284:27)
I/flutter ( 9042): #3      AxisChartPainter.paint (package:fl_chart/src/chart/base/axis_chart/axis_chart_painter.dart:40:5)
I/flutter ( 9042): #4      LineChartPainter.paint (package:fl_chart/src/chart/line_chart/line_chart_painter.dart:79:11)
I/flutter ( 9042): #5      RenderLineChart.paint (package:fl_chart/src/chart/line_chart/line_chart_renderer.dart:75:14)
I/flutter ( 9042): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
...(more stack trace)
```

The error was caused by passing a `maxY` argument of 0 to a line chart, which is admittedly a mistake on my part. But it took me so much time to figure out what the problem is. It would be so much more ergonomic if the various constructors had assertions which verify the input, and let the developer if they passed in something invalid. That way the error messages would be much more meaningful.

**Comment by imaNNeoFighT** [comment]
Hi. Can you please give me a reproducible code with the latest version of `fl_chart`?
I couldn't reproduce it.
